name 'wirbelsturm-redis'
version '1.0.5'
source 'https://github.com/miguno/puppet-redis.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary      'Module for managing and configuring Redis'
description  'Module for managing and configuring Redis'
project_page 'https://github.com/miguno/puppet-redis'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
#DISABLED SO WE DO NOT DEPEND ON PUPPETFORGE#dependency 'puppetlabs/stdlib', '>= 4.1.0'
